source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!
use_frameworks!

target 'Segment-Appboy_Example' do
  platform :ios, '9.0'
  pod "Segment-Appboy", :path => "../", :inhibit_warnings => false
  pod 'Analytics'
end

target 'Segment-Appboy_Tests' do
  platform :ios, '9.0'
  pod "Segment-Appboy", :path => "../", :inhibit_warnings => false
  pod 'Analytics'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end
